[phases.setup]
nixPkgs = [
  "glib",
  "gtk3",
  "pango",
  "cairo",
  "gdk-pixbuf",
  "fontconfig",
  "freetype",
  "harfbuzz",
  "fribidi",
  "libffi",
  "libxml2",
  "libxslt",
  "zlib",
  "libjpeg",
  "libpng"
]
